# Generated by Django 5.1.3 on 2024-11-19 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudfunc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='descriptionn',
            new_name='description',
        ),
    ]
